name: Release

on:
  pull_request_target:
    branches:
      - 'main'
    types:
      - closed

jobs:

  autorelease:
    name: AutoRelease
    if: |
      startsWith(github.event.pull_request.title, 'New Release - docker-overdrive -> v') &&
      github.event.label.name == 'release' &&
      github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rm -rf .git/hooks

      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install js-yaml

      - name: "Release"
        id: create-release
        uses: "actions/github-script@v7.0.1"
        with:
          github-token: "${{ secrets.PAT }}"
          script: |
            const script = require('./.github/workflows/github-release/github-create-release.js')
            return await script({github, context, core})
