# https://docs.github.com/en/actions

name: "Trigger Release"

on:
  workflow_dispatch:

jobs:
  trigger-release:
    name: Trigger Release

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - run: rm -rf .git/hooks

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install js-yaml

      - name: "Trigger Release Check"
        id: release_prep
        uses: "actions/github-script@v7.0.1"
        with:
          script: |
            const script = require('./.github/workflows/github-release/github-release-check.js')
            return await script({github, context, core})

      - uses: tibdex/github-app-token@v2
        id: get_bot_token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
        with:
          token: ${{ steps.get_bot_token.outputs.token }}
          branch: release/docker-overdrive
          title: New Release - docker-overdrive -> ${{ env.TAG_NAME }}
          commit-message: New Release - docker-overdrive -> ${{ env.TAG_NAME }}
          body: |
            Update the release version of `docker-overdrive` to the latest version
          labels: release
