name: BaseImage Updater
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Modify the specific files using scripts
        run: |
          sh update-baseimage.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/overdrive-autoupdate
          title: Auto-update BaseImage Script
          commit-message: Auto-update BaseImage Script
          body: |
            Update the version of the BaseImage to the latest version
          labels: dependencies
