name: Overdrive Updater
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  auto-update-overdrive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -rf .git/hooks

      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install js-yaml

      - name: "Check for BaseImage Updates"
        id: update_checker
        uses: "actions/github-script@v7.0.1"
        with:
          script: |
            const script = require('./.github/workflows/updaters/update-overdrive.js')
            return await script({github, core})

      - uses: tibdex/github-app-token@v2
        id: get_bot_token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.get_bot_token.outputs.token }}
          branch: update/overdrive-autoupdate
          title: Auto-update Overdrive Script
          commit-message: Auto-update Overdrive
          body: |
            Update the version of the Overdrive to the latest version
          labels: dependencies
