name: Overdrive Updater
on:
  schedule:
    - cron: '0 4 * * 0'
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Modifiy the specific files using scripts
        run: |
          sh update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/overdrive-autoupdate
          title: Auto-update Overdrive Script
          commit-message: Auto-update Overdrive Script
          body: |
            Update the version of the Overdrive script to the latest version
          labels: dependencies